[hekad]
maxprocs = 2

[NsqInput]
lookupd_http_addresses = [ "http://nsqlookupd-1.in.opsee.com:4161", "http://nsqlookupd-2.in.opsee.com:4161" ]
topic = "_.heartbeat"
channel = "heka-opsee"
max_in_flight = 4

[HeartbeatFilter]
type = "SandboxFilter"
message_matcher = "Type == 'nsq.input'"
ticker_interval = 0
filename = "lua_filters/heartbeat_filter.lua"
preserve_data = false
can_exit = false
output_limit = 32768

[librato_encoder]
type = "SandboxEncoder"
filename = "lua_encoders/librato_encoder.lua"
preserve_data = false

[debug_output]
type = "LogOutput"
message_matcher = "Type == 'heka.sandbox.heartbeat'"
encoder = "RstEncoder"

[RstEncoder]

[DashboardOutput]
ticker_interval = 15

[librato]
type = "HttpOutput"
method = "POST"
message_matcher = "Type == 'heka.sandbox.heartbeat'"
encoder = "librato_encoder"
address = "https://metrics-api.librato.com/v1/metrics"
#address = "http://requestb.in/wktjvawk"
username = "greg@opsee.com"
password = "f5aba57d1cf6cdf9b2583fab0e55d7ae596cce771acd74dc4c31ff0664b510b4"
    [librato.headers]
    Content-Type = ["application/json"]

