[hekad]
maxprocs = 2

[NsqInput]
lookupd_http_addresses = [ "http://nsqlookupd-1.in.opsee.com:4161" ]
topic = "_.connected"
channel = "mike-heka-dev#ephemeral"
decoder = "JsonDecoder"

[JsonDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/json.lua"

[HeartbeatDecoder]

[cbuf_librato_encoder]
type = "SandboxEncoder"
filename = "lua_encoders/cbuf_librato.lua"
preserve_data = true

# [librato]
# type = "HttpOutput"
# message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'cbuf'"
# encoder = "cbuf_librato_encoder"
# address = "https://metrics-api.librato.com/v1/metrics"
# username = "jdixon@librato.com"
# password = "f48c781b49f43b8fe991e004978b9717abd8e065b9656abeb476dc3ac44480fe"
#     [librato.headers]
#     Content-Type = ["application/json"]

